# Generated by Django 3.1 on 2020-08-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Escuela')),
                ('cursos', models.IntegerField(default=0, verbose_name='Num Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_fecha', models.CharField(max_length=45, verbose_name='Dia')),
                ('hora_ini', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profesor', models.CharField(max_length=45, verbose_name='Id Profesor')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='HoraProfePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.IntegerField(default=0, verbose_name='Carga Horaria')),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.periodo')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Nombre Curso')),
                ('secciones', models.IntegerField(default=0, verbose_name='Numero Secciones')),
                ('escuela_nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc_t', models.CharField(default='', max_length=45)),
                ('nrc_p', models.CharField(default='', max_length=45)),
                ('nrc_l', models.CharField(default='', max_length=45)),
                ('aula', models.CharField(max_length=45, verbose_name='Aula')),
                ('cargaHora', models.IntegerField(default=0, verbose_name='Carga Horaria')),
                ('curso_nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.curso')),
                ('escuela_nombre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.escuela')),
                ('fecha_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.fecha')),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.bloque')),
                ('fecha_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.fecha')),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.periodo')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horario.profesor')),
            ],
        ),
    ]
