# Generated by Django 3.1 on 2020-08-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_auto_20200805_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='cargaHora',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='secciones',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Numero Secciones'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='cursos',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Num Cursos'),
        ),
        migrations.AlterField(
            model_name='horaprofeperiodo',
            name='carga',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Carga Horaria'),
        ),
    ]
